version: "3.9"

services:
  mysql:
    image: taohongqiang/it-devops-mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: Leoch@@20260101
      MYSQL_DATABASE: devops
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 5s
      timeout: 5s
      retries: 20

  redis:
    image: taohongqiang/it-devops-redis:latest
    command: ["redis-server", "--requirepass", "Leoch@@20260101"]
    ports:
      - "6379:6379"
    volumes:
      - ./docker/redis:/data
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "Leoch@@20260101", "ping"]
      interval: 5s
      timeout: 5s
      retries: 10

  devops-admin:
    image: taohongqiang/it-devops-admin:latest
    container_name: it-devops-devops-admin
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_DRUID_URL: jdbc:mysql://mysql:3306/devops?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&nullCatalogMeansCurrent=true
      SPRING_DATASOURCE_DRUID_USERNAME: root
      SPRING_DATASOURCE_DRUID_PASSWORD: Leoch@@20260101
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: "6379"
      SPRING_DATA_REDIS_PASSWORD: Leoch@@20260101
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - "10001:10001"
    volumes:
      - ./docker/admin/logs:/app/logs

  nginx:
    image: taohongqiang/it-devops-ui:latest
    container_name: it-devops-nginx
    depends_on:
      devops-admin:
        condition: service_started
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/logs:/var/log/nginx
