spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/devops?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&nullCatalogMeansCurrent=true
    username: root
    password: Leoch@@20260101
    hikari:
      minimum-idle: 10
      maximum-pool-size: 100
      connection-timeout: 6000
      idle-timeout: 300000
      max-lifetime: 600000
  data:
    redis:
      database: 0
      host: 192.168.210.136
      port: 6379
      password: Leoch@@20260101
      timeout: 6000ms
      lettuce:
        pool:
          max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
          max-wait: -1ms      # 连接池最大阻塞等待时间（使用负值表示没有限制）
          max-idle: 10      # 连接池中的最大空闲连接
          min-idle: 5       # 连接池中的最小空闲连接
knife4j:
  enable: false
  basic:
    enable: false
    username: admin
    password: admin
  setting:
    enableFooter: false